# Generated by Django 3.2.7 on 2022-11-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_index', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('url', models.SlugField(max_length=64, unique=True)),
                ('content', tinymce.models.HTMLField(max_length=5000, verbose_name='Content')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('edited_datetime', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_index'],
            },
        ),
    ]
